![jupyter](./Week1-01.png)

2.张量有三种表现形式
标量是一维；
向量是二维；
矩阵是多维

3.data，device，grad，等等

In [1]:
import torch

In [2]:
import numpy as np

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
out = torch.from_numpy(arr)

print("arr:",arr,"torch_arr:",out)
print("\narr id:", id(arr), "torch id:", id(out))

arr: [[1 2 3]
 [4 5 6]] torch_arr: tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

arr id: 1532542876928 torch id: 1532542914992


5.一共四种形式  

In [7]:
mean = torch.arange(1,5,dtype=torch.float)
std = torch.arange(1,5, dtype=torch.float)
arr = torch.normal(mean, std)
print(arr)

tensor([-0.7703, -0.3832, -3.2059, -2.4602])


In [8]:
mean = 4
std = torch.arange(1,5, dtype=torch.float)
arr = torch.normal(mean, std)
print(arr)

tensor([2.3605, 3.4353, 4.8067, 5.9473])


In [9]:
arr = torch.normal(1.,5., size=(4,))
print(arr)

tensor([  5.5815,   3.7341,   5.4345, -10.4446])
